### ISSUE TITLE
Add piranha-server-helloworld template

### ISSUE THREAD

**Issue by mnriem** [piranhacloud/piranha-server-helloworld#1]

**Comment by mnriem** [comment]
@Thihup Can you validate this GitHub project template. Note it is set to 21.12.0 so locally you will have to set it to 21.12.0-SNAPSHOT as the 21.12.0 is not out yet ;)

**Comment by Thihup** [comment]
@mnriem Working as expected ;)

**Comment by mnriem** [comment]
Thanks for checking!
