### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by mnriem** [piranhacloud/piranha-server-helloworld#3]

**Comment by muzakkirsaifi123** [comment]
May I do this?? Please assign to me..

**Comment by mnriem** [comment]
Sure go ahead!

**Comment by mnriem** [comment]
@muzakkirsaifi123 And how is it going?

**Comment by mnriem** [comment]
I am closing this one as I have not found anyone to pick it up or found time to work on it myself.
